# Generated by Django 4.1.3 on 2022-11-23 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShortUrl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=100)),
                ('redirect_url', models.CharField(max_length=200)),
                ('hit_count', models.IntegerField(default=0)),
            ],
        ),
    ]
